# Generated by Django 5.1.15 on 2026-09-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Platform Super Admin'), ('HEAD_MANAGER', 'Tenant Head Manager'), ('MANAGER', 'Tenant Manager'), ('STAFF', 'Tenant Staff'), ('STUDENT', 'Online Student')], db_index=True, default='STAFF', max_length=32),
        ),
    ]
