# Generated by Django 5.1.15 on 2026-09-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_scope',
            field=models.CharField(choices=[('ALL', 'All Tenant Data'), ('BRANCH_ONLY', 'Own Branch Only')], default='ALL', max_length=16),
        ),
    ]
