# Generated by Django 5.1.15 on 2026-08-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='icon',
            field=models.CharField(blank=True, default='Building2', max_length=100),
        ),
    ]
