# Generated by Django 5.1.15 on 2026-08-21 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_majoroption_schooldirectory'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'crm_b2b_partners',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VisaStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('passport', models.CharField(db_index=True, max_length=50)),
                ('birthday', models.CharField(blank=True, max_length=50, null=True)),
                ('visa_type', models.CharField(default='Embassy', max_length=50)),
                ('application_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=100)),
                ('application_date', models.CharField(blank=True, max_length=50, null=True)),
                ('status_date', models.CharField(blank=True, max_length=50, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('tariff', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinator', models.CharField(blank=True, max_length=100, null=True)),
                ('b2b', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('refund_application', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('batch_selected', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Visa Student',
                'verbose_name_plural': 'Visa Students',
                'db_table': 'crm_visa_students',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'passport'], name='crm_visa_st_tenant__47c776_idx'), models.Index(fields=['tenant', 'status'], name='crm_visa_st_tenant__5cf21b_idx'), models.Index(fields=['tenant', 'is_deleted'], name='crm_visa_st_tenant__7fdaf2_idx'), models.Index(fields=['tenant', 'pinned'], name='crm_visa_st_tenant__e96f16_idx')],
                'unique_together': {('tenant', 'passport')},
            },
        ),
    ]
