# Generated by Django 5.1.15 on 2026-08-26 11:07

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_universityoption_tenant_and_defaults'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_color', models.CharField(blank=True, max_length=50, null=True)),
                ('task_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_user_preferences', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_student_user_preferences',
                'indexes': [models.Index(fields=['tenant', 'user'], name='crm_student_tenant__7f27d5_idx'), models.Index(fields=['student', 'user'], name='crm_student_student_2dfd22_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'user'), name='uniq_student_user_preference')],
            },
        ),
    ]
