# Generated by Django 5.1.15 on 2026-08-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_b2boption_visastudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_1_status',
            field=models.CharField(blank=True, default='Chosen', max_length=50, null=True),
        ),
    ]
