# Generated by Django 5.1.15 on 2026-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentuserpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
