# Generated by Django 5.1.15 on 2026-09-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_normalize_student_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Immutable payment anchor. Set once on creation (P + student id). Never changes.', max_length=55, null=True, unique=True),
        ),
    ]
