# Generated by Django 5.1.15 on 2026-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_populate_payment_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffoption',
            name='contract_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
