# Generated by Django 5.1.15 on 2026-09-13 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_tariffoption_contract_text'),
        ('tenants', '0002_branch_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('template_name', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField(help_text='Structured HTML document content')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sent', 'Yuborilgan'), ('viewed', "Ko'rildi"), ('signed', 'Imzolangan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('sign_token', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_user_agent', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='students.student')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='contracts_tenant__3657e3_idx'), models.Index(fields=['tenant', 'is_deleted'], name='contracts_tenant__2581c6_idx'), models.Index(fields=['tenant', 'contract_number'], name='contracts_tenant__5bd9c9_idx')],
            },
        ),
    ]
