# Generated by Django 5.1.15 on 2026-09-15 03:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_contractauditevent_emailverificationcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
