# Generated by Django 5.1.15 on 2026-09-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_contract_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
