# Generated by Django 5.1.15 on 2026-09-16 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_contract_is_archived'),
        ('tenants', '0002_branch_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_permanently_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='permanently_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'is_permanently_deleted'], name='students_tenant__b20547_idx'),
        ),
    ]
