# Generated by Django 5.1.15 on 2026-09-16 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_is_permanently_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitleDirectory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'job_title_directory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkplaceDirectory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'workplace_directory',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='father_workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
