import uuid
from django.db import migrations


WORKPLACE_NAMES = [
    "Akademik litsey", "Arxiv muassasasi", "Arxitektura tashkiloti", "Auditorlik tashkiloti",
    "Aviachipta agentligi", "Aviakompaniya", "Avtomobil ehtiyot qismlari korxonasi",
    "Avtomobil ishlab chiqarish korxonasi", "Avtomobil import kompaniyasi", "Avtomobil servis markazi",
    "Avtosalon", "Avtoservis", "Avtobus korxonasi", "Avtotransport korxonasi", "Axborot agentligi",
    "Axborot markazi", "Axborot texnologiyalari kompaniyasi",
    "Bank", "Baliqchilik xo'jaligi", "Boshqaruv kompaniyasi", "Bojxona tashkiloti", "Bog'cha",
    "Bog'dorchilik xo'jaligi", "Bozor", "Bolalar bog'chasi", "Bolalar markazi", "Bolalar oromgohi",
    "Bolalar sport maktabi",
    "Chet eldagi kompaniya", "Chet eldagi korxona", "Chakana savdo korxonasi", "Chakana savdo do'koni",
    "Chorvachilik xo'jaligi", "Chet el tashkiloti",
    "Davlat agentligi", "Davlat arxivi", "Davlat banki", "Davlat byudjet tashkiloti", "Davlat korxonasi",
    "Davlat qo'mitasi", "Davlat muassasasi", "Davlat tashkiloti", "Davlat universiteti",
    "Davlat klinikasi", "Davlat maktabi", "Dasturiy ta'minot kompaniyasi", "Dehqon xo'jaligi",
    "Diagnostika markazi", "Diplomatik vakolatxona", "Dizayn studiyasi", "Dispanser", "Dorixona",
    "Drayverlik kompaniyasi", "Dori ishlab chiqarish korxonasi",
    "Elektr energetika korxonasi", "Elektr tarmoqlari korxonasi", "Elektronika ishlab chiqarish korxonasi",
    "Elektron tijorat kompaniyasi", "Energetika kompaniyasi", "Eksport kompaniyasi",
    "Ekspertiza markazi", "Ekologiya tashkiloti", "Ekoturizm tashkiloti", "Elchixona",
    "Favqulodda vaziyatlar tashkiloti", "Fermer xo'jaligi", "Filarmoniya", "Fond", "Fotostudiya",
    "Fuqarolik jamiyati tashkiloti", "Futbol klubi", "Farmatsevtika kompaniyasi",
    "Farmatsevtika korxonasi", "Franchayzing kompaniyasi", "Fuqarolik aviatsiyasi tashkiloti",
    "Gaz ta'minoti korxonasi", "Geologiya tashkiloti", "Go'sht mahsulotlari korxonasi",
    "Go'zallik saloni", "Gumanitar markaz", "Gidroenergetika korxonasi",
    "Harbiy akademiya", "Harbiy qism", "Harbiy korxona", "Harbiy tashkilot", "Havo transporti kompaniyasi",
    "Hokimlik", "Hududiy boshqarma", "Hududiy davlat tashkiloti", "Huquqiy maslahat markazi",
    "Huquqni muhofaza qiluvchi organ", "Hunarmandchilik korxonasi", "Hunarmandlar markazi",
    "Hujjatlashtirish markazi",
    "Ichki ishlar organi", "Import kompaniyasi", "Informatsion texnologiyalar kompaniyasi",
    "Innovatsion markaz", "Institut", "Internet provayder", "Iqtisodiyot tashkiloti",
    "Ishlab chiqarish korxonasi", "Ishlab chiqarish zavodi", "Issiqlik elektr stansiyasi",
    "Issiqlik ta'minoti korxonasi", "Ixtisoslashtirilgan maktab", "Ixtisoslashtirilgan tibbiyot markazi",
    "Ijtimoiy xizmat markazi", "Ilmiy tadqiqot instituti", "Ilmiy markaz", "Ilmiy tashkilot",
    "Ipoteka tashkiloti", "IT kompaniyasi", "IT markazi",
    "Jamoat tashkiloti", "Jamoatchilik markazi", "Jamoat fondi", "Jamoat birlashmasi",
    "Jismoniy tarbiya va sport tashkiloti", "Jurnal tahririyati", "Jurnal nashriyoti",
    "Jahon tashkilotining mahalliy vakolatxonasi",
    "Kadrlar markazi", "Kadrlar tayyorlash markazi", "Kadrlar agentligi", "Kafe", "Kasalxona",
    "Kasaba tashkiloti", "Kasb-hunar maktabi", "Kasb-hunar markazi", "Kasanachilik korxonasi",
    "Kimyo sanoati korxonasi", "Kinoteatr", "Kommunal xizmat korxonasi", "Konsalting kompaniyasi",
    "Kontent kompaniyasi", "Korxona", "Kredit tashkiloti", "Klinik diagnostika markazi", "Kollej",
    "Kutubxona", "Ko'ngilochar markaz", "Ko'chmas mulk kompaniyasi", "Ko'chmas mulk agentligi",
    "Kompyuter savdo kompaniyasi", "Kompyuter servis markazi", "Kosmetik mahsulotlar korxonasi",
    "Kurort", "Kuryerlik kompaniyasi",
    "Laboratoriya", "Logistika kompaniyasi", "Logistika markazi", "Lizing kompaniyasi",
    "Loyiha instituti", "Loyihalash tashkiloti", "Litsenziyalash tashkiloti",
    "Madaniyat markazi", "Maishiy xizmat ko'rsatish markazi", "Marketing agentligi", "Mahalla",
    "Mahalliy hokimlik", "Mahalliy davlat tashkiloti", "Mahsulot ishlab chiqarish korxonasi",
    "Mashinasozlik korxonasi", "Media kompaniyasi", "Mehmonxona", "Metallurgiya korxonasi",
    "Mikromoliya tashkiloti", "Mineral suv ishlab chiqarish korxonasi", "Moliya tashkiloti",
    "Moliya kompaniyasi", "Moliya instituti", "Monopoliyaga qarshi tashkilot", "Muzey",
    "Musiqa maktabi", "Marketing kompaniyasi", "Mahsulot yetkazib berish kompaniyasi",
    "Metro korxonasi", "Mobil aloqa kompaniyasi", "Matbaa korxonasi",
    "Nafaqada", "Neft kompaniyasi", "Neft-gaz korxonasi", "Nodavlat ta'lim muassasasi",
    "Nodavlat tashkilot", "Nodavlat universitet", "Notarial idora", "Nonvoyxona", "Nashriyot",
    "Nashriyot uyi", "Narkologiya markazi", "Nevrologiya markazi",
    "Navoiy kon-metallurgiya korxonasi turidagi korxona", "Nufuzli xalqaro tashkilot vakolatxonasi",
    "Oliy majlis tizimidagi tashkilot", "Oliy ta'lim muassasasi", "Oliy maktab",
    "Oliy harbiy ta'lim muassasasi", "Oilaviy korxona", "Oilaviy poliklinika", "Oilaviy shifoxona",
    "Omborxona", "O'quv markazi", "O'rmon xo'jaligi", "Oziq-ovqat ishlab chiqarish korxonasi",
    "Oziq-ovqat savdo korxonasi", "O'zini o'zi band qilgan", "O'zbekistondagi xalqaro tashkilot vakolatxonasi",
    "O'zbekiston Respublikasi vazirligi", "O'zbekiston Respublikasi agentligi",
    "O'zbekiston Respublikasi qo'mitasi", "O'zbekiston Respublikasi inspeksiyasi",
    "O'zbekiston Respublikasi davlat tashkiloti",
    "Pochta bo'limi", "Pochta kompaniyasi", "Poliklinika", "Professional ta'lim muassasasi",
    "Professional maktab", "Prokuratura", "Prokuratura organi", "Psixologik markaz",
    "Pedagogika instituti", "Poligrafiya korxonasi", "Plastik mahsulotlar ishlab chiqarish korxonasi",
    "Printer servis markazi",
    "Qandolat mahsulotlari korxonasi", "Qandolatchilik korxonasi", "Qishloq xo'jaligi korxonasi",
    "Qishloq xo'jaligi shirkati", "Qishloq xo'jaligi markazi", "Qishloq xo'jaligi universiteti",
    "Qishloq vrachlik punkti", "Qora metallurgiya korxonasi", "Qurilish kompaniyasi",
    "Qurilish korxonasi", "Qurilish materiallari korxonasi", "Qurilish tashkiloti",
    "Qutqaruv xizmati", "Qadoqlash korxonasi", "Qandolat fabrikasi", "Qayta ishlash korxonasi",
    "Qayta ishlash zavodi",
    "Radio stansiya", "Reklama agentligi", "Respublika miqyosidagi davlat tashkiloti",
    "Respublikadagi davlat muassasasi", "Restoran", "Reabilitatsiya markazi",
    "Rieltorlik kompaniyasi", "Rivojlantirish markazi", "Raqamli xizmatlar kompaniyasi",
    "Raqamli texnologiyalar markazi", "Raqamli media kompaniyasi",
    "Sanitariya markazi", "Sanoat korxonasi", "Savdo markazi", "Savdo korxonasi", "Savdo do'koni",
    "Savdo kompaniyasi", "Sellyuloza-qog'oz korxonasi", "Sertifikatlashtirish markazi",
    "Sog'liqni saqlash muassasasi", "Sog'liqni saqlash tashkiloti", "Soliq tashkiloti",
    "Soliq inspeksiyasi", "Sport maktabi", "Sport federatsiyasi", "Sport klubi", "Sport markazi",
    "Sug'urta kompaniyasi", "Sug'urta tashkiloti", "Suv ta'minoti korxonasi", "Supermarket", "Sud",
    "Sud tashkiloti", "Sud ekspertizasi markazi", "Stomatologiya klinikasi", "Stomatologiya markazi",
    "Statistika tashkiloti", "Startup kompaniya", "Sanoat zonasi korxonasi",
    "Sanoat parkidagi korxona", "Sertifikatlash tashkiloti", "Soliq bo'limi",
    "Sanitariya-epidemiologiya xizmati", "Sezilarli darajadagi davlat tashkiloti",
    "Ta'lim markazi", "Ta'lim muassasasi", "Ta'mirlash korxonasi", "Taksi xizmati",
    "Tashqi savdo kompaniyasi", "Tashqi ishlar tizimidagi tashkilot", "Telekommunikatsiya kompaniyasi",
    "Temir yo'l korxonasi", "Texnika universiteti", "Texnikum", "Texnologik institut",
    "Texnologiyalar markazi", "Televizion kanal", "Televiziya kompaniyasi", "Tibbiyot markazi",
    "Tibbiyot muassasasi", "Tibbiyot instituti", "Tikuvchilik korxonasi", "To'qimachilik korxonasi",
    "Transport korxonasi", "Transport kompaniyasi", "Turizm kompaniyasi", "Turizm markazi",
    "Tuman hokimligi", "Tuman tibbiyot birlashmasi", "Tuman davlat tashkiloti", "Tuman maktabi",
    "Tuman poliklinikasi", "Tuman shifoxonasi", "Tijorat banki", "Tijorat tashkiloti",
    "Tadbirkorlik subyekti", "Tadbirkorlik markazi", "Texnik xizmat ko'rsatish markazi",
    "Ulgurji savdo korxonasi", "Ulgurji savdo kompaniyasi", "Umumta'lim maktabi",
    "Umumiy amaliyot klinikasi", "Universitet", "Universitet klinikasi",
    "Universitet qoshidagi markaz", "Universitet tashkiloti", "Universitet instituti",
    "Uskunalar ishlab chiqarish korxonasi", "Uy xo'jaligi", "Uy-joy kommunal xizmat korxonasi",
    "Vazirlik", "Vazirlik huzuridagi tashkilot", "Viloyat hokimligi", "Viloyat davlat tashkiloti",
    "Viloyat tibbiyot birlashmasi", "Viloyat poliklinikasi", "Viloyat shifoxonasi", "Vokzal",
    "Vokzal boshqarmasi", "Veterinariya klinikasi", "Veterinariya markazi",
    "Xalqaro kompaniya", "Xalqaro tashkilot", "Xalqaro universitet", "Xalqaro maktab",
    "Xalq ta'limi tizimidagi tashkilot", "Xizmat ko'rsatish korxonasi", "Xizmat ko'rsatish markazi",
    "Xususiy bank", "Xususiy biznes", "Xususiy klinika", "Xususiy korxona", "Xususiy maktab",
    "Xususiy kompaniya", "Xususiy universitet", "Xususiy o'quv markazi", "Xususiy tadbirkorlik",
    "Xususiy tibbiyot muassasasi", "Xususiy shifoxona", "Xususiy bog'cha", "Xususiy institut",
    "Xususiy kollej", "Xususiy texnikum", "Xorijiy kompaniya", "Xorijiy vakolatxona",
    "Xorijiy tashkilot", "Xostel",
    "Yetkazib berish kompaniyasi", "Yuk tashish kompaniyasi", "Yuridik kompaniya",
    "Yuridik maslahat markazi", "Yoshlar markazi", "Yoshlar tashkiloti", "Yoshlar sport maktabi",
    "Yer tuzish tashkiloti", "Yer kadastri tashkiloti", "Yirik sanoat korxonasi",
    "Yengil sanoat korxonasi",
    "Zavod", "Zargarlik korxonasi", "Zargarlik do'koni", "Zootexnika xo'jaligi",
    "Ziyorat turizmi tashkiloti",
    "Ishlamaydi", "Vaqtincha ishsiz", "Pensiyada", "Vafot etgan", "Chet elda ishlaydi", "Uy bekasi",
    "Talaba", "O'quvchi", "Harbiy xizmatda", "Xususiy tadbirkor", "Oilaviy biznes", "Shaxsiy biznes",
    "Freelancer", "Kasanachi", "Fermer", "Dehqon", "Boshqa",
    "Adliya tashkiloti", "Adliya boshqarmasi", "Adliya vazirligi", "Bandlik markazi",
    "Bandlik boshqarmasi", "Bandlik tashkiloti", "Budjet tashkiloti", "Byudjetdan tashqari tashkilot",
    "Davlat xizmatlari markazi", "Davlat aktivlarini boshqarish tashkiloti",
    "Davlat kadastr tashkiloti", "Davlat sanitariya xizmati", "Davlat statistika tashkiloti",
    "Davlat soliq xizmati", "Davlat tibbiyot muassasasi", "Davlat veterinariya xizmati",
    "Ekologiya boshqarmasi", "Energetika vazirligi tizimidagi tashkilot", "Farmatsevtika agentligi",
    "Investitsiya kompaniyasi", "Investitsiya fondi", "Kadastr tashkiloti", "Migratsiya tashkiloti",
    "Migratsiya markazi", "Oliy attestatsiya tashkiloti", "Prokuratura boshqarmasi",
    "Qishloq xo'jaligi vazirligi tizimidagi tashkilot", "Raqamli hukumat markazi",
    "Soliq boshqarmasi", "Ta'lim boshqarmasi", "Tashqi savdo tashkiloti",
    "Tashqi ishlar vazirligi tizimidagi tashkilot", "Turizm qo'mitasi",
    "Vazirlik tizimidagi tashkilot", "Viloyat boshqarmasi", "Yoshlar ishlari tashkiloti",
    "Yoshlar ishlari agentligi", "Xotin-qizlar tashkiloti", "Mahalla idorasi",
    "Fuqarolar yig'ini", "Kasaba uyushmasi tashkiloti", "Advokatlik byurosi", "Advokatlik firmasi",
    "Huquqiy xizmat ko'rsatish tashkiloti", "Konsullik", "Xalqaro fond", "Xalqaro loyiha tashkiloti",
    "Xayriya tashkiloti", "Xayriya fondi", "Nodavlat notijorat tashkiloti", "NNT",
    "Diniy tashkilot", "Masjid", "Diniy ta'lim muassasasi", "Cherkov", "Madaniyat muassasasi",
    "Madaniyat saroyi", "Teatr", "San'at maktabi", "Ijod markazi", "Ko'rgazma markazi",
    "Kongress markazi", "Konsert zali", "Sport majmuasi", "Stadion", "Suzish havzasi",
    "Fitnes markazi", "Sog'lomlashtirish markazi", "Sanatoriy", "Kurort-sanatoriy",
    "Diagnostika markazi", "Laboratoriya markazi", "Tibbiy laboratoriya", "Qon markazi",
    "Epidemiologiya markazi", "Sanitariya-epidemiologiya markazi", "Onkologiya markazi",
    "Kardiologiya markazi", "Travmatologiya markazi", "Pediatriya markazi", "Perinatal markaz",
    "Tug'ruqxona", "Shoshilinch tibbiy yordam markazi", "Hayvonlar klinikasi",
    "Tashkilot ko'rsatilmagan", "Ish joyi noma'lum", "Ma'lumot mavjud emas", "Hozirda ishlamaydi",
    "Rasmiy ish joyi mavjud emas", "Norasmiy ishlaydi", "Mustaqil faoliyat", "Xususiy faoliyat",
    "Oilaviy faoliyat", "Mavsumiy ish", "Vaqtinchalik ish", "Chet elda vaqtincha ishlaydi",
    "Chet elda doimiy ishlaydi", "Tashkilot yopilgan", "Korxona faoliyatini to'xtatgan",
    "Ish joyi o'zgargan", "Ish joyi aniqlanmagan", "Nafaqaxo'r",
]

JOB_TITLE_NAMES = [
    "Agronom", "Administrator", "Advokat", "Agent", "Analitik", "Arxivchi", "Arxitektor", "Auditor",
    "Aviasoz", "Aviatsiya muhandisi", "Aviakassa operatori", "Aviadispetcher", "Avtomexanik",
    "Avtomobil haydovchisi", "Avtomobil ustasi", "Avtobus haydovchisi", "Avtotransport dispetcheri",
    "Avtoelektrik", "Avtoservis ustasi", "Axborot texnologiyalari mutaxassisi",
    "Bank xodimi", "Bank menejeri", "Bank operatori", "Bosh buxgalter", "Bosh direktor",
    "Bosh iqtisodchi", "Bosh muhandis", "Bosh mutaxassis", "Boshqaruvchi", "Bosh inspektor",
    "Bosh energetik", "Bosh agronom", "Bog'bon", "Bojxona inspektori", "Buxgalter",
    "Dasturchi", "Dizayner", "Dispetcher", "Direktor", "Direktor o'rinbosari",
    "Departament boshlig'i", "Dehqon", "Diagnostika mutaxassisi", "Diplomatik xodim",
    "Dorixona mudiri", "Dorixona farmatsevti", "Dori sotuvchisi", "Duradgor", "Dastgoh operatori",
    "Elektrik", "Elektr muhandisi", "Elektr montajchi", "Energetik", "Ekolog", "Ekspert",
    "Ekspert-maslahatchi", "Ekskavatorchi", "Elektr tarmoqlari mutaxassisi",
    "Elektr stansiyasi operatori", "Elektronika muhandisi",
    "Farmatsevt", "Farmatsevtika mutaxassisi", "Fermer", "Filolog", "Fotograf",
    "Foydalanuvchilar bilan ishlash mutaxassisi", "Fizioterapevt", "Finansist", "Frontend dasturchi",
    "Frizer", "Fermer xo'jaligi rahbari", "Favqulodda vaziyatlar xodimi",
    "Geolog", "Geodezist", "Gid", "Gidrometeorolog", "Grafik dizayner", "Gazchi",
    "Gaz ta'minoti mutaxassisi", "Gvardiya xodimi", "G'isht teruvchi",
    "Haydovchi", "Hamshira", "Hisobchi", "Huquqshunos", "Hakam", "Hujjatlar bo'yicha mutaxassis",
    "Harbiy xizmatchi", "Harbiy ofitser", "Harbiy shifokor", "Harbiy muhandis", "Hokim",
    "Hokim o'rinbosari",
    "Ichki ishlar xodimi", "Ijrochi direktor", "Iqtisodchi", "Ilmiy xodim", "Ilmiy tadqiqotchi",
    "Informatika o'qituvchisi", "Inspektor", "Ish boshqaruvchi", "Ishlab chiqarish ustasi",
    "Ishlab chiqarish muhandisi", "Ishchi", "Issiqlik texnigi", "IT mutaxassisi", "IT menejer",
    "IT administrator", "Ijtimoiy xodim", "Imtihon nazoratchisi", "Inventarizatsiya mutaxassisi",
    "Jurnalist", "Jismoniy tarbiya o'qituvchisi", "Jamoatchilik bilan aloqalar mutaxassisi",
    "Jarroh", "Jo'natmalar operatori",
    "Kadrlar bo'yicha mutaxassis", "Kadrlar menejeri", "Kassa operatori", "Kassir",
    "Kasb-hunar o'qituvchisi", "Kimyogar", "Kimyo muhandisi", "Kinematograf", "Konditer",
    "Konstruktor", "Konchi", "Korxona rahbari", "Korxona direktori", "Kran operatori",
    "Kredit mutaxassisi", "Kredit menejeri", "Kuryer", "Kutubxonachi", "Kiberxavfsizlik mutaxassisi",
    "Kontent menejer", "Koordinator", "Kompyuter operatori", "Kompyuter muhandisi",
    "Kompyuter texnigi", "Ko'rsatmalar bo'yicha mutaxassis", "Ko'chmas mulk agenti",
    "Laborant", "Laboratoriya mudiri", "Logist", "Logistika menejeri", "Loyiha menejeri",
    "Loyihachi", "Loyiha rahbari", "Lizing mutaxassisi",
    "Magistr", "Marketing mutaxassisi", "Marketing menejeri", "Marketolog", "Ma'mur", "Menejer",
    "Mexanik", "Mexanik muhandis", "Metallurg", "Metall kesuvchi", "Metallga ishlov beruvchi",
    "Mehnat muhofazasi mutaxassisi", "Mehmonxona administratori", "Mehmonxona menejeri",
    "Moliya mutaxassisi", "Moliya menejeri", "Muhandis", "Muxbir", "Mudir", "Muassasa rahbari",
    "Muallim", "Musiqa o'qituvchisi", "Muzey xodimi", "Maktab direktori",
    "Maktab direktori o'rinbosari", "Maktab o'qituvchisi", "Maktab psixologi",
    "Maktab xo'jalik mudiri", "Maktab laboranti", "Maslahatchi",
    "Nafaqaxo'r", "Notarius", "Notarius yordamchisi", "Nashriyot xodimi", "Nonvoy", "Nazoratchi",
    "Neft muhandisi", "Neft-gaz mutaxassisi", "Narkolog", "Nevropatolog",
    "Noutbuk/kompyuter texnigi", "NNT xodimi", "Noshir", "Navbatchi",
    "O'qituvchi", "O'quv ishlari bo'yicha direktor o'rinbosari", "Operator", "Ombor mudiri",
    "Omborchi", "Ombor operatori", "Oliy toifali mutaxassis", "Oliy toifali o'qituvchi",
    "Oziq-ovqat texnologi", "Oqartirish ustasi", "O'lchovchi", "O'rmonchi",
    "O'zini o'zi band qilgan", "Oshpaz", "Oshxona mudiri", "Oila shifokori", "O'simlikshunos",
    "Pedagog", "Pediatr", "Psixolog", "Poyezd mashinisti", "Poyezd kuzatuvchisi",
    "Pochta operatori", "Politsiya xodimi", "Poliklinika mudiri", "Prokuror",
    "Prokuror yordamchisi", "Provizor", "Pardozchi", "Payvandchi", "Poydevorchi",
    "Printer operatori", "PR mutaxassisi", "Personal menejeri",
    "Qassob", "Qadoqlovchi", "Qandolatchi", "Qishloq xo'jaligi mutaxassisi",
    "Qishloq xo'jaligi muhandisi", "Qorovul", "Qutqaruvchi", "Quruvchi", "Qurilish muhandisi",
    "Qurilish ustasi", "Qurilish brigadiri", "Quduq burg'ilovchi", "Qayta ishlash operatori",
    "Qaychi ustasi", "Qabul bo'limi xodimi", "Qabulxona administratori",
    "Rejissyor", "Reklama mutaxassisi", "Reklama menejeri", "Rieltor", "Rektor",
    "Rektor o'rinbosari", "Rahbar", "Rahbar o'rinbosari", "Restoran menejeri",
    "Restoran administratori", "Rassom", "Reabilitolog", "Radiolog", "Radio operator",
    "Radiotexnik", "Raqamli marketing mutaxassisi", "Rivojlanish bo'yicha menejer",
    "Sartarosh", "Sanoat muhandisi", "Savdo menejeri", "Savdogar", "Sotuvchi",
    "Sotuv bo'yicha mutaxassis", "Sotuv menejeri", "SMM mutaxassisi", "Soliq inspektori",
    "Soliq mutaxassisi", "Sotuv operatori", "Suv ta'minoti mutaxassisi", "Sug'urta agenti",
    "Sug'urta mutaxassisi", "Sug'urta menejeri", "Sudya", "Sud kotibi", "Sud eksperti",
    "Stomatolog", "Slesar", "Smeta mutaxassisi", "Smena boshlig'i", "Sifat nazoratchisi",
    "Sifat bo'yicha menejer", "Ssenarist", "Sport murabbiyi", "Sportchi", "Statistik",
    "Sartarosh-usta", "Sog'liqni saqlash mutaxassisi", "Sanitar", "Sanitariya shifokori",
    "Server administratori", "Sistemachi",
    "Tadbirkor", "Ta'lim bo'yicha mutaxassis", "Ta'lim menejeri", "Ta'lim tashkiloti rahbari",
    "Ta'mirlash ustasi", "Taksi haydovchisi", "Tashkilot rahbari", "Texnik", "Texnolog",
    "Texnolog-muhandis", "Telekommunikatsiya mutaxassisi", "Temirchi", "Temir yo'l xodimi",
    "Tibbiyot xodimi", "Tibbiyot muhandisi", "Tibbiyot vakili", "Tibbiyot texnigi", "Tikuvchi",
    "Tikuvchilik ustasi", "Tizim administratori", "Tizim muhandisi", "Tizim tahlilchisi",
    "To'quvchi", "Traktorchi", "Trener", "Transport menejeri", "Transport dispetcheri",
    "Turizm menejeri", "Turizm agenti", "Tarbiyachi", "Tahlilchi", "Tovarshunos",
    "Tovar menejeri", "Tovar qabul qiluvchi", "Tashqi savdo mutaxassisi",
    "Tashqi iqtisodiy faoliyat mutaxassisi",
    "Usta", "Usta yordamchisi", "Ulgurji savdo menejeri", "Universitet rektori",
    "Universitet professori", "Universitet o'qituvchisi", "Universitet dekani",
    "Universitet kafedra mudiri", "Universitet ilmiy xodimi", "Ustoz", "Uskunalar operatori",
    "Uskuna sozlovchi", "Uchuvchi", "Usta-quruvchi",
    "Vazir", "Vazir o'rinbosari", "Viloyat hokimi", "Viloyat hokimi o'rinbosari", "Veterinar",
    "Veterinariya shifokori", "Videograf", "Vrach", "Vrach-terapevt", "Vrach-jarroh",
    "Vrach-pediatr", "Vrach-kardiolog", "Vrach-stomatolog", "Vokzal boshlig'i", "Vokzal xodimi",
    "Xavfsizlik xodimi", "Xavfsizlik muhandisi", "Xizmatchi", "Xodim", "Xo'jalik mudiri",
    "Xo'jalik ishchisi", "Xorijiy til o'qituvchisi", "Xususiy tadbirkor", "Xususiy shifokor",
    "Xususiy o'qituvchi", "Xususiy biznes egasi", "Xizmat ko'rsatish xodimi",
    "Xalqaro aloqalar mutaxassisi", "Xalqaro savdo mutaxassisi", "Xazinachi",
    "Xodimlar bo'yicha mutaxassis",
    "Yuridik maslahatchi", "Yurist", "Yuridik bo'lim boshlig'i", "Yordamchi", "Yordamchi direktor",
    "Yordamchi muhandis", "Yetkazib beruvchi", "Yuk tashuvchi", "Yuk mashinasi haydovchisi",
    "Yuk ortuvchi", "Yuk tushiruvchi", "Yotoqxona mudiri", "Yoshlar bilan ishlash mutaxassisi",
    "Yer tuzuvchi", "Yer kadastri mutaxassisi",
    "Zavod direktori", "Zavod ishchisi", "Zavod muhandisi", "Zargar", "Zootexnik",
    "Zilzila xavfsizligi mutaxassisi",
    "Ishchi-xodim", "Ishsiz", "Vaqtincha ishsiz", "Ishlamaydi", "Nafaqada", "Pensiyada",
    "Vafot etgan", "Uy bekasi", "Talaba", "O'quvchi", "Harbiy xizmatda", "Harbiy nafaqaxo'r",
    "Chet elda ishlaydi", "Chet elda vaqtincha ishlaydi", "Xususiy tadbirkor", "Fermer", "Dehqon",
    "Kasanachi", "Freelancer", "Mustaqil mutaxassis", "Oilaviy biznes egasi", "Biznes egasi",
    "Kompaniya egasi", "Korxona egasi", "Boshqa", "Lavozimi noma'lum", "Ma'lumot mavjud emas",
    "Lavozimi ko'rsatilmagan", "Rasmiy lavozimi yo'q", "Norasmiy ishlaydi", "Mavsumiy ishchi",
    "Vaqtinchalik ishchi", "Mustaqil ishchi", "Yollanma ishchi", "Oilaviy xo'jalik xodimi",
    "Professor", "Dotsent", "Katta o'qituvchi", "Assistent", "Metodist", "Metodist-o'qituvchi",
    "Ilmiy kotib", "Kafedra mudiri", "Dekan", "Dekan o'rinbosari", "Prorektor",
    "Pedagog-psixolog", "Logoped", "Defektolog", "Ma'naviy-ma'rifiy ishlar mutaxassisi",
    "O'quv bo'limi mutaxassisi", "Ta'lim sifatini nazorat qilish mutaxassisi",
    "O'quv ishlari bo'yicha mutaxassis", "Ilmiy bo'lim xodimi",
    "Bosh shifokor", "Bosh shifokor o'rinbosari", "Shifokor", "Terapevt", "Kardiolog", "Nevrolog",
    "Onkolog", "Urolog", "Ginekolog", "Akusher-ginekolog", "Oftalmolog", "Otorinolaringolog",
    "Dermatolog", "Endokrinolog", "Psixiatr", "Infeksionist", "Anesteziolog", "Reanimatolog",
    "Feldsher", "Tibbiy registrator", "Tibbiy texnik", "Tibbiy vakil", "Bosh hamshira",
    "Hamshira mudiri",
    "Qo'mita raisi", "Qo'mita raisi o'rinbosari", "Agentlik direktori", "Agentlik rahbari",
    "Boshqarma boshlig'i", "Bo'lim boshlig'i", "Sektor rahbari", "Yetakchi mutaxassis",
    "Katta mutaxassis", "Mutaxassis", "Yetakchi inspektor", "Referent", "Kotib",
    "Ish yurituvchi", "Davlat xizmatchisi", "Davlat inspektori", "Hokim yordamchisi", "Mutasaddi",
]


def seed_directories(apps, schema_editor):
    WorkplaceDirectory = apps.get_model('students', 'WorkplaceDirectory')
    JobTitleDirectory = apps.get_model('students', 'JobTitleDirectory')

    # dict.fromkeys preserves first-seen order while dropping duplicates -
    # the source lists above contain some intentional overlaps (e.g. "Boshqa",
    # "Nafaqada" appear in more than one category of the curated list).
    workplace_names = list(dict.fromkeys(WORKPLACE_NAMES))
    job_names = list(dict.fromkeys(JOB_TITLE_NAMES))

    WorkplaceDirectory.objects.bulk_create(
        [WorkplaceDirectory(id=uuid.uuid4(), name=n) for n in workplace_names],
        ignore_conflicts=True,
    )
    JobTitleDirectory.objects.bulk_create(
        [JobTitleDirectory(id=uuid.uuid4(), name=n) for n in job_names],
        ignore_conflicts=True,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_occupation_directories'),
    ]

    operations = [
        migrations.RunPython(seed_directories, noop_reverse),
    ]
