# Generated by Django 5.1.15 on 2026-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_seed_occupation_directories'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tariff_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
