# Generated by Django 5.1.15 on 2026-09-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_add_guardian_appendix_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='guardian_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='guardian_full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='guardian_passport_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='guardian_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='guardian_relation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='guardian_signature_data',
            field=models.TextField(blank=True, default='', help_text='Base64 data URL of guardian signature'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_minor',
            field=models.BooleanField(default=False, help_text='Student was under 18 at signing time'),
        ),
    ]
