# Generated by Django 5.1.15 on 2026-09-22 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_add_contract_guardian_fields'),
        ('tenants', '0002_branch_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('phone_local', models.CharField(blank=True, default='', max_length=20)),
                ('phone_type', models.CharField(choices=[('phone1', 'Talaba telefoni 1'), ('guardian_phone', 'Kafil telefoni')], db_index=True, max_length=20)),
                ('firebase_uid', models.CharField(blank=True, default='', max_length=128)),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'crm_phone_verification_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_token', 'is_used'], name='crm_phone_v_session_9e3f5a_idx'), models.Index(fields=['phone', 'tenant'], name='crm_phone_v_phone_ed4ef5_idx')],
            },
        ),
    ]
