# Generated by Django 5.1.15 on 2026-09-25 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_add_contract_guardian_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='didit', max_length=20)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('session_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('document_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('PENDING_REVIEW', 'Pending Student Review'), ('VERIFIED', 'Verified'), ('DECLINED', 'Declined'), ('ABANDONED', 'Abandoned')], db_index=True, default='NOT_STARTED', max_length=20)),
                ('raw_decision', models.JSONField(blank=True, null=True)),
                ('extracted_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('face_match_result', models.CharField(blank=True, max_length=20, null=True)),
                ('liveness_result', models.CharField(blank=True, max_length=20, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verifications', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Identity Verification',
                'verbose_name_plural': 'Identity Verifications',
                'db_table': 'crm_identity_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
