# Generated by Django 5.1.15 on 2026-10-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_identityverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mother_workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
